spring:
  datasource:
    url: jdbc:h2:mem:pc_parts;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migration-h2
